//============================================================================
// Klax OKI MSM6295-compatible ADPCM Sound Chip
//
// MAME reference (0.288, cached under /mame):
//   okim6295.cpp / okiadpcm.cpp; klax.cpp configures
//   OKIM6295(config, "oki", 14.318181 MHz / 4 / 4, PIN7_HIGH) and maps byte
//   read/write at 0x270001 on the 68000 lower data lane.
//
// Verified bit-exact against a MAME-0.288-equivalent golden model by
// core/tb/tb_klax_oki6295_parity.v (vectors from core/sim/make_oki_golden.py
// using the real Klax sample ROMs).
//
// Behavioral contract (matches MAME exactly):
//   - Command protocol: a byte with bit 7 latches a pending sample number;
//     the next byte (any value, even with bit 7 set) is the second half:
//     voice mask in bits 7:4, volume index in bits 3:0. A non-pending byte
//     without bit 7 stops the voices in bits 6:3.
//   - A start request for an already-playing voice is ignored.
//   - Phrase table entry n at byte n*8: 3-byte big-endian start/stop, each
//     masked to 0x3FFFF; valid iff start < stop (strict); the phrase spans
//     2*(stop-start+1) nibbles beginning at the high nibble of `start`.
//   - The MAME region is 0x40000 bytes with only 0x00000-0x1FFFF loaded
//     from ROM; the rest is zero-filled, so byte reads above 128KB return
//     0x00 (phrases reaching there decode silence-ish ramps, busy stays
//     set for the programmed length).
//   - Status read returns 0xF0 | playing-voice bits.
//   - Output: per voice trunc_toward_zero(signal * volume / 32), summed
//     and scaled so one full-volume voice spans the full 16-bit range:
//     audio = clamp(16 * sum, -32768, +32767). This is the integer-exact
//     equivalent of MAME's float stream (add_int scale 2048, stream unit
//     mapped to 32768).
//
// Timing:
//   - Sample rate is XTAL/16/132 = 6779.44 Hz, generated by a fractional
//     accumulator (long-term exact for any CLK_HZ, jitter <= 1 clk).
//   - wr_en is edge-qualified: the 68000 holds the write strobe for the
//     whole AS/DTACK overlap (many clk cycles), but one bus write must
//     process exactly one command byte.
//   - The busy bit rises a few hundred ns after the second command byte
//     (phrase table fetch); MAME models it as instant. The real chip also
//     asserts busy with a delay, and the gap is far below one sample
//     period, so the CPU cannot observe the difference.
//============================================================================

module klax_oki6295 #(
    parameter CLK_HZ       = 20000000,  // clk frequency
    parameter XTAL_HZ      = 14318181,  // board master crystal
    parameter XTAL_PREDIV  = 16,        // XTAL -> OKI clock (/4 /4 on board)
    parameter OKI_DIVISOR  = 132        // pin 7 high: 132 OKI clocks/sample
) (
    input               clk,
    input               reset,

    input               rd_en,
    input               wr_en,
    input       [7:0]   wr_data,
    output      [7:0]   rd_data,

    input               ioctl_download,
    input       [15:0]  ioctl_index,
    input               ioctl_wr,
    input       [26:0]  ioctl_addr,
    input       [7:0]   ioctl_dout,

    output reg  [15:0]  audio_sample,
    // 894886.3 Hz chip clock enable, exported so the board-level analog
    // output filter (klax_audio_filter.v) can derive its own rate from the
    // same accumulator instead of duplicating it and drifting.
    output              oki_clk_en,
    output      [15:0]  debug_flags
);

    // 128KB of sample ROM backing the low half of the 256KB address space.
    localparam ROM_AW = 17;
    localparam ROM_DEPTH = 1 << ROM_AW;

    // Phrase addresses are 18 bits (masked to 0x3FFFF like MAME); nibble
    // addresses carry one extra LSB.
    localparam PHRASE_AW = 18;

    (* ramstyle = "M10K" *) reg [7:0] rom [0:ROM_DEPTH-1];
    reg [ROM_AW-1:0] rom_rd_addr = {ROM_AW{1'b0}};
    reg [7:0] rom_q = 8'd0;

    wire oki_ioctl_wr = ioctl_download && ioctl_wr &&
                        (ioctl_index == 16'd3) &&
                        (ioctl_addr[26:ROM_AW] == {(27-ROM_AW){1'b0}});

    always @(posedge clk) begin
        if (oki_ioctl_wr)
            rom[ioctl_addr[ROM_AW-1:0]] <= ioctl_dout;
        rom_q <= rom[rom_rd_addr];
    end

    // === Sample tick generator ===
    // Stage 1 recreates the 894886.3125 Hz OKI clock from clk with a
    // fractional accumulator; stage 2 is the chip's /132 sample divider.
    localparam [31:0] ACC_LIMIT = CLK_HZ * XTAL_PREDIV;

    reg [31:0] xtal_acc = 32'd0;
    reg oki_en = 1'b0;
    reg [7:0] oki_div_ctr = 8'd0;
    reg sample_tick = 1'b0;

    always @(posedge clk or posedge reset) begin
        if (reset) begin
            xtal_acc <= 32'd0;
            oki_en <= 1'b0;
            oki_div_ctr <= 8'd0;
            sample_tick <= 1'b0;
        end else begin
            if (xtal_acc + XTAL_HZ >= ACC_LIMIT) begin
                xtal_acc <= xtal_acc + XTAL_HZ - ACC_LIMIT;
                oki_en <= 1'b1;
            end else begin
                xtal_acc <= xtal_acc + XTAL_HZ;
                oki_en <= 1'b0;
            end

            sample_tick <= 1'b0;
            if (oki_en) begin
                if (oki_div_ctr == OKI_DIVISOR - 1) begin
                    oki_div_ctr <= 8'd0;
                    sample_tick <= 1'b1;
                end else begin
                    oki_div_ctr <= oki_div_ctr + 8'd1;
                end
            end
        end
    end

    assign oki_clk_en = oki_en;

    // === Voice state ===
    reg [PHRASE_AW:0] voice_nibble_addr [0:3];
    reg [PHRASE_AW:0] voice_stop_nibble [0:3];
    reg signed [11:0] voice_signal [0:3];
    reg [5:0] voice_step [0:3];
    reg [3:0] voice_volume [0:3];
    reg [3:0] voice_active = 4'd0;

    assign rd_data = {4'b1111, voice_active};

    // === Command register state ===
    reg wr_en_d = 1'b0;
    wire wr_strobe = wr_en && !wr_en_d;

    reg [6:0] pending_cmd = 7'd0;
    reg pending_valid = 1'b0;

    reg start_pending = 1'b0;
    reg [6:0] start_sample = 7'd0;
    reg [3:0] start_mask = 4'd0;
    reg [3:0] start_volume = 4'd0;

    // === Phrase table fetch FSM ===
    reg [2:0] table_state = 3'd0;
    reg [2:0] table_count = 3'd0;
    reg [6:0] table_sample = 7'd0;
    reg [3:0] table_mask = 4'd0;
    reg [3:0] table_volume = 4'd0;
    reg [PHRASE_AW-1:0] table_start = {PHRASE_AW{1'b0}};
    reg [PHRASE_AW-1:0] table_stop = {PHRASE_AW{1'b0}};

    localparam TABLE_IDLE = 3'd0;
    localparam TABLE_REQ  = 3'd1;
    localparam TABLE_WAIT = 3'd2;
    localparam TABLE_CAPTURE = 3'd3;
    localparam TABLE_DONE = 3'd4;

    // === Playback FSM ===
    reg tick_req = 1'b0;
    reg [2:0] play_state = 3'd0;
    reg [2:0] play_voice = 3'd0;
    reg [PHRASE_AW:0] play_nibble_addr = {(PHRASE_AW+1){1'b0}};
    reg play_in_zero = 1'b0;
    reg signed [15:0] mix_acc = 16'sd0;
    // Multiply operands registered between the ADPCM decode (PLAY_DECODE) and
    // the mix accumulate (PLAY_MIX). The signal*volume product + 16-bit
    // accumulate were one ~19 ns path that broke setup at 57.27 MHz; splitting
    // the multiply into its own clk closes it. mix_signal holds the full 13-bit
    // next_signal (not the 12-bit stored voice_signal) so the result is exact.
    reg signed [12:0] mix_signal = 13'sd0;
    reg [3:0]         mix_volume = 4'd0;

    localparam PLAY_IDLE   = 3'd0;
    localparam PLAY_REQ    = 3'd1;
    localparam PLAY_WAIT   = 3'd2;
    localparam PLAY_DECODE = 3'd3;
    localparam PLAY_NEXT   = 3'd4;
    localparam PLAY_DONE   = 3'd5;
    localparam PLAY_MIX    = 3'd6;

    // ROM read port arbitration: the playback burst has priority, the
    // phrase table fetch retries until the port is free.
    wire play_rom_req = (play_state == PLAY_REQ) &&
                        !play_voice[2] && voice_active[play_voice];
    wire tick_consume = (play_state == PLAY_IDLE) && tick_req;

    // Byte feeding the decoder: addresses above the 128KB ROM load read as
    // 0x00 (MAME zero-fills the unloaded top half of the 0x40000 region).
    wire [7:0] zone_byte = play_in_zero ? 8'h00 : rom_q;

    reg dbg_write_seen = 1'b0;
    reg dbg_start_seen = 1'b0;
    reg dbg_stop_seen = 1'b0;
    reg dbg_rom_load_seen = 1'b0;
    reg dbg_audio_nonzero_seen = 1'b0;
    reg dbg_status_read_seen = 1'b0;

    assign debug_flags = {
        1'b1,
        5'd0,
        dbg_status_read_seen,
        dbg_audio_nonzero_seen,
        dbg_rom_load_seen,
        dbg_stop_seen,
        dbg_start_seen,
        dbg_write_seen,
        voice_active
    };

    integer i;
    always @(posedge clk or posedge reset) begin
        if (reset) begin
            wr_en_d <= 1'b0;
            pending_cmd <= 7'd0;
            pending_valid <= 1'b0;
            start_pending <= 1'b0;
            start_sample <= 7'd0;
            start_mask <= 4'd0;
            start_volume <= 4'd0;
            table_state <= TABLE_IDLE;
            table_count <= 3'd0;
            table_sample <= 7'd0;
            table_mask <= 4'd0;
            table_volume <= 4'd0;
            table_start <= {PHRASE_AW{1'b0}};
            table_stop <= {PHRASE_AW{1'b0}};
            voice_active <= 4'd0;
            tick_req <= 1'b0;
            play_state <= PLAY_IDLE;
            play_voice <= 3'd0;
            play_nibble_addr <= {(PHRASE_AW+1){1'b0}};
            play_in_zero <= 1'b0;
            mix_acc <= 16'sd0;
            mix_signal <= 13'sd0;
            mix_volume <= 4'd0;
            audio_sample <= 16'd0;
            rom_rd_addr <= {ROM_AW{1'b0}};
            dbg_write_seen <= 1'b0;
            dbg_start_seen <= 1'b0;
            dbg_stop_seen <= 1'b0;
            dbg_rom_load_seen <= 1'b0;
            dbg_audio_nonzero_seen <= 1'b0;
            dbg_status_read_seen <= 1'b0;

            for (i = 0; i < 4; i = i + 1) begin
                voice_nibble_addr[i] <= {(PHRASE_AW+1){1'b0}};
                voice_stop_nibble[i] <= {(PHRASE_AW+1){1'b0}};
                voice_signal[i] <= 12'sd0;
                voice_step[i] <= 6'd0;
                voice_volume[i] <= 4'd0;
            end
        end else begin
            wr_en_d <= wr_en;
            tick_req <= sample_tick | (tick_req & ~tick_consume);

            if (rd_en)
                dbg_status_read_seen <= 1'b1;
            if (oki_ioctl_wr)
                dbg_rom_load_seen <= 1'b1;

            // === Phrase table fetch FSM ===
            case (table_state)
                TABLE_IDLE: begin
                    if (start_pending) begin
                        start_pending <= 1'b0;
                        table_sample <= start_sample;
                        table_mask <= start_mask;
                        table_volume <= start_volume;
                        table_count <= 3'd0;
                        table_start <= {PHRASE_AW{1'b0}};
                        table_stop <= {PHRASE_AW{1'b0}};
                        table_state <= TABLE_REQ;
                    end
                end

                TABLE_REQ: begin
                    if (!play_rom_req) begin
                        rom_rd_addr <= {{(ROM_AW-10){1'b0}}, table_sample, 3'b000}
                                       + {{(ROM_AW-3){1'b0}}, table_count};
                        table_state <= TABLE_WAIT;
                    end
                end

                TABLE_WAIT: begin
                    table_state <= TABLE_CAPTURE;
                end

                TABLE_CAPTURE: begin
                    case (table_count)
                        3'd0: table_start[17:16] <= rom_q[1:0];
                        3'd1: table_start[15:8]  <= rom_q;
                        3'd2: table_start[7:0]   <= rom_q;
                        3'd3: table_stop[17:16]  <= rom_q[1:0];
                        3'd4: table_stop[15:8]   <= rom_q;
                        3'd5: table_stop[7:0]    <= rom_q;
                        default: begin end
                    endcase

                    if (table_count == 3'd5)
                        table_state <= TABLE_DONE;
                    else begin
                        table_count <= table_count + 3'd1;
                        table_state <= TABLE_REQ;
                    end
                end

                TABLE_DONE: begin
                    if (table_start < table_stop) begin
                        for (i = 0; i < 4; i = i + 1) begin
                            if (table_mask[i] && !voice_active[i]) begin
                                voice_active[i] <= 1'b1;
                                voice_nibble_addr[i] <= {table_start, 1'b0};
                                voice_stop_nibble[i] <= {table_stop, 1'b1};
                                voice_signal[i] <= 12'sd0;
                                voice_step[i] <= 6'd0;
                                voice_volume[i] <= table_volume;
                            end
                        end
                    end
                    table_state <= TABLE_IDLE;
                end

                default: table_state <= TABLE_IDLE;
            endcase

            // === Playback FSM ===
            case (play_state)
                PLAY_IDLE: begin
                    if (tick_req) begin
                        mix_acc <= 16'sd0;
                        play_voice <= 3'd0;
                        play_state <= PLAY_REQ;
                    end
                end

                PLAY_REQ: begin
                    if (play_voice[2]) begin
                        play_state <= PLAY_DONE;
                    end else if (voice_active[play_voice]) begin
                        play_nibble_addr <= voice_nibble_addr[play_voice];
                        rom_rd_addr <= voice_nibble_addr[play_voice][ROM_AW:1];
                        play_in_zero <= voice_nibble_addr[play_voice][PHRASE_AW];
                        play_state <= PLAY_WAIT;
                    end else begin
                        play_state <= PLAY_NEXT;
                    end
                end

                PLAY_WAIT: begin
                    play_state <= PLAY_DECODE;
                end

                PLAY_DECODE: begin
                    decode_voice(play_voice,
                                 play_nibble_addr[0] ? zone_byte[3:0]
                                                     : zone_byte[7:4]);
                    play_state <= PLAY_MIX;
                end

                PLAY_MIX: begin
                    // Deferred multiply+accumulate (operands registered last
                    // clk in PLAY_DECODE). Bit-identical to the original
                    // single-cycle decode_voice mix.
                    mix_acc <= mix_acc + mix_dac(mix_signal, mix_volume);
                    play_state <= PLAY_NEXT;
                end

                PLAY_NEXT: begin
                    play_voice <= play_voice + 3'd1;
                    play_state <= PLAY_REQ;
                end

                PLAY_DONE: begin
                    audio_sample <= mix_clamp(mix_acc);
                    if (mix_clamp(mix_acc) != 16'd0)
                        dbg_audio_nonzero_seen <= 1'b1;
                    play_state <= PLAY_IDLE;
                end

                default: play_state <= PLAY_IDLE;
            endcase

            // === Command register ===
            // Placed after the FSMs so that a stop command in the same clk
            // as a phrase-table completion wins (CPU write order: the start
            // was requested first, the stop arrived later).
            if (wr_strobe) begin
                dbg_write_seen <= 1'b1;
                if (pending_valid) begin
                    // Second half of a two-byte start command. Any byte is
                    // consumed here, even one with bit 7 set (MAME: the
                    // voice mask is simply bits 7:4).
                    pending_valid <= 1'b0;
                    start_pending <= 1'b1;
                    start_sample <= pending_cmd;
                    start_mask <= wr_data[7:4];
                    start_volume <= wr_data[3:0];
                    if (wr_data[7:4] != 4'd0)
                        dbg_start_seen <= 1'b1;
                end else if (wr_data[7]) begin
                    pending_cmd <= wr_data[6:0];
                    pending_valid <= 1'b1;
                end else begin
                    // Silence command: stop voices in bits 6:3, including
                    // ones whose start is still in the table-fetch pipeline.
                    for (i = 0; i < 4; i = i + 1) begin
                        if (wr_data[3 + i]) begin
                            voice_active[i] <= 1'b0;
                            table_mask[i] <= 1'b0;
                            start_mask[i] <= 1'b0;
                        end
                    end
                    if (wr_data[6:3] != 4'd0)
                        dbg_stop_seen <= 1'b1;
                end
            end
        end
    end

    task decode_voice;
        input [2:0] voice;
        input [3:0] nibble;
        reg signed [12:0] next_signal;
        reg [5:0] next_step;
        reg [PHRASE_AW+1:0] next_nibble_addr;
        begin
            next_signal = clip12(voice_signal[voice] + adpcm_delta(voice_step[voice], nibble));
            next_step = clip_step(voice_step[voice], step_delta(nibble[2:0]));
            next_nibble_addr = {1'b0, voice_nibble_addr[voice]} + 1'd1;

            voice_signal[voice] <= next_signal[11:0];
            voice_step[voice] <= next_step;
            voice_nibble_addr[voice] <= next_nibble_addr[PHRASE_AW:0];

            // Register the multiply operands; the signal*volume product and the
            // accumulate run next clk in PLAY_MIX. The full 13-bit next_signal
            // is kept so the deferred product is bit-identical to the original.
            mix_signal <= next_signal;
            mix_volume <= voice_volume[voice];

            if (next_nibble_addr > {1'b0, voice_stop_nibble[voice]})
                voice_active[voice] <= 1'b0;
        end
    endtask

    // signal * volume_fraction with MAME's truncate-toward-zero rounding then
    // a >>>5 scale. Split out of decode_voice so the multiply gets its own clk
    // (PLAY_MIX); the arithmetic is identical to the original inline version.
    function signed [14:0] mix_dac;
        input signed [12:0] sig;
        input [3:0] vol;
        reg signed [19:0] prod;
        begin
            prod = sig * volume_level(vol);
            mix_dac = (prod + (prod[19] ? 20'sd31 : 20'sd0)) >>> 5;
        end
    endfunction

    // clamp(16 * sum, -32768, +32767): one full-volume voice spans the
    // full output range; concurrent loud voices saturate, exactly like
    // MAME's stream conversion.
    function [15:0] mix_clamp;
        input signed [15:0] acc;
        begin
            if (acc > 16'sd2047)
                mix_clamp = 16'h7FFF;
            else if (acc < -16'sd2048)
                mix_clamp = 16'h8000;
            else
                mix_clamp = acc <<< 4;
        end
    endfunction

    function signed [12:0] clip12;
        input signed [13:0] value;
        begin
            if (value > 14'sd2047)
                clip12 = 13'sd2047;
            else if (value < -14'sd2048)
                clip12 = -13'sd2048;
            else
                clip12 = value[12:0];
        end
    endfunction

    function [5:0] clip_step;
        input [5:0] step;
        input signed [4:0] delta;
        reg signed [7:0] sum;
        begin
            // $signed() on the zero-extended step keeps the addition signed
            // so a negative delta sign-extends instead of zero-extending.
            sum = $signed({2'b00, step}) + delta;
            if (sum < 0)
                clip_step = 6'd0;
            else if (sum > 8'sd48)
                clip_step = 6'd48;
            else
                clip_step = sum[5:0];
        end
    endfunction

    function signed [4:0] step_delta;
        input [2:0] code;
        begin
            case (code)
                3'd0, 3'd1, 3'd2, 3'd3: step_delta = -5'sd1;
                3'd4: step_delta = 5'sd2;
                3'd5: step_delta = 5'sd4;
                3'd6: step_delta = 5'sd6;
                default: step_delta = 5'sd8;
            endcase
        end
    endfunction

    function [11:0] step_value;
        input [5:0] step;
        begin
            case (step)
                6'd0:  step_value = 12'd16;
                6'd1:  step_value = 12'd17;
                6'd2:  step_value = 12'd19;
                6'd3:  step_value = 12'd21;
                6'd4:  step_value = 12'd23;
                6'd5:  step_value = 12'd25;
                6'd6:  step_value = 12'd28;
                6'd7:  step_value = 12'd31;
                6'd8:  step_value = 12'd34;
                6'd9:  step_value = 12'd37;
                6'd10: step_value = 12'd41;
                6'd11: step_value = 12'd45;
                6'd12: step_value = 12'd50;
                6'd13: step_value = 12'd55;
                6'd14: step_value = 12'd60;
                6'd15: step_value = 12'd66;
                6'd16: step_value = 12'd73;
                6'd17: step_value = 12'd80;
                6'd18: step_value = 12'd88;
                6'd19: step_value = 12'd97;
                6'd20: step_value = 12'd107;
                6'd21: step_value = 12'd118;
                6'd22: step_value = 12'd130;
                6'd23: step_value = 12'd143;
                6'd24: step_value = 12'd157;
                6'd25: step_value = 12'd173;
                6'd26: step_value = 12'd190;
                6'd27: step_value = 12'd209;
                6'd28: step_value = 12'd230;
                6'd29: step_value = 12'd253;
                6'd30: step_value = 12'd279;
                6'd31: step_value = 12'd307;
                6'd32: step_value = 12'd337;
                6'd33: step_value = 12'd371;
                6'd34: step_value = 12'd408;
                6'd35: step_value = 12'd449;
                6'd36: step_value = 12'd494;
                6'd37: step_value = 12'd544;
                6'd38: step_value = 12'd598;
                6'd39: step_value = 12'd658;
                6'd40: step_value = 12'd724;
                6'd41: step_value = 12'd796;
                6'd42: step_value = 12'd876;
                6'd43: step_value = 12'd963;
                6'd44: step_value = 12'd1060;
                6'd45: step_value = 12'd1166;
                6'd46: step_value = 12'd1282;
                6'd47: step_value = 12'd1411;
                default: step_value = 12'd1552;
            endcase
        end
    endfunction

    function signed [13:0] adpcm_delta;
        input [5:0] step;
        input [3:0] nibble;
        reg [11:0] stepval;
        reg [12:0] diff;
        begin
            stepval = step_value(step);
            diff = {1'b0, (stepval >> 3)};
            if (nibble[0])
                diff = diff + (stepval >> 2);
            if (nibble[1])
                diff = diff + (stepval >> 1);
            if (nibble[2])
                diff = diff + stepval;

            if (nibble[3])
                adpcm_delta = -{1'b0, diff};
            else
                adpcm_delta = {1'b0, diff};
        end
    endfunction

    // MAME okim6295 volume table: ~3dB steps, indexes >= 9 are silent.
    // Signed so the signal product stays a signed multiply.
    function signed [6:0] volume_level;
        input [3:0] volume;
        begin
            case (volume)
                4'h0: volume_level = 7'sd32;
                4'h1: volume_level = 7'sd22;
                4'h2: volume_level = 7'sd16;
                4'h3: volume_level = 7'sd11;
                4'h4: volume_level = 7'sd8;
                4'h5: volume_level = 7'sd6;
                4'h6: volume_level = 7'sd4;
                4'h7: volume_level = 7'sd3;
                4'h8: volume_level = 7'sd2;
                default: volume_level = 7'sd0;
            endcase
        end
    endfunction

endmodule
